### PR TITLE
Major improvements

### PR DESCRIPTION
**Pull request by wdlkmpx**
- reduce code
- increase log verbosity
- rename build-all.sh to build.sh
- build.conf: build only needed programs by default
- build.conf: INITRD_PROGS variable containing
            the list of apps to be copied to
            the locally generated initrd.gz
- build.conf: add comments
- build.sh: add command line options:
  - -pkg pkg    : compile specific pkg only
  - -all        : force building all *_static pkgs
  - -copyall    : use all generated binaries to create initrd.gz
                otherwise only the ones specified in
                INITRD_PROGS='..' in build.conf
  - -arch target: compile for target arch
  - -sysgcc     : use system gcc
  - -help       : show help and exit
- can now compile for all targets available at landley.net
  with -arch <target> option (see ./build.sh -help)
- to keep things a bit simple the only other alternative to build
  is the system gcc since the musl cross compilers cover most cases
  (needs testing but only in unsupported musl targets...)
- remove 0initrd/bin 0logs 0sources so that it's easier
  to clean up and add commits
- store binaries in 00_${ARCH}/bin
- store logs in 00_${ARCH}/log
- 00_${ARCH} and 0sources are created at runtime
- update e2fsprogs to version 1.43 (17-May-2016)
- update README.md
- misc edits/fixes

These changes provide the framework to experiment at will
with the targets/packages.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
After this I want to add the init script from the main repo and toy with it, to test all the changes, just run ./build.sh and create a initrd.gz file, everything is generated from scratch.

**Comment by wdlkmpx** [comment]
Hi micko I think I'm going a bit too far, far beyond what this is supposed to be.

I added another huge commit, which includes some fixes
an edited /init and /sbin/wait4usb*. More details in https://github.com/puppylinux-woof-CE/initrd_progs/pull/5/commits/9227c8780e78b6c05919add6f013fc587d1fa83d

And yes, it actually works just like before

You may close this now or leave it open if you wish.

**Comment by wdlkmpx** [comment]
I forgot to mention that i tested these last edits, using a clean project to download, extract, compile, etc, and generate the initrd.gz file, to spot some bugs introduced before, so now I think it's ready to be tested in a usb frugall install for example, replacing the initrd.gz and rebooting and see how it reaches the desktop without issues... that's whay I did.

**Comment by 01micko** [comment]
> Hi micko I think I'm going a bit too far, far beyond what this is supposed to be.

Why? I started this as a clunky way to reproduce the initrd static programs. You have removed some clunkiness and added support for arm, and managed to wrap it all up in an initrd.gz. This is exactly what we need I think and it probably should be in the next iteration of woof, whatever that may be.  :joy_cat: 

I'll leave it open for a bit until I can test it and may even try a native build on my odroid U3. It has a samsung exynos quad core.

**Comment by wdlkmpx** [comment]
OK, I'll keep adding commits, fine-tuning the "default" build. Just a few hours ago was 2.1MB complete, not it's 1.9MB.. in i486, x86_64 has about the same size, and arm is a little bigger.

I'm also constantly checking the busybox git log to see news, modutils have been patched for 1.24 and there's more patches in git for 1.25.

I always work with the latest version of all apps. I'll disable the full 'modutils', and test. Only lsmod is used in the 'huge' init script. Then perhaps I'll disable the 'full' find.. apparently the busybox version has all the features used in the init script.

**Comment by 01micko** [comment]
Broke down at disktype.

@ line 225 this helps

`disktype_static) static_bins='disktype' ;;`

**Comment by wdlkmpx** [comment]
I can't find that line, are you using the latest commit?

**Comment by 01micko** [comment]
Downloaded the tarball.. 

Anyway, i have this:

```
_# stat -c %s initrd.gz 
2170595
```

For 64, about to boot it. Back soon.

**Comment by 01micko** [comment]
Ok, it boots fine but there is a network issue and some conflict with PVM. Maybe new busybox?

I run a static IP over cat 6 and usually have no issue but each reboot I had to reconfigure network. I tried DHCPCD too, same thing. I'll have to go through the boot logs to see what is happening.

**Comment by 01micko** [comment]
> Broke down at disktype.

Ok, cloned repo and that problem has disappeared.

**Comment by 01micko** [comment]
Ok, rebuilt from latest commit and all is now working well, including network and PVM :grinning:

**Comment by 01micko** [comment]
I'll merge this and just offer more PRs whenever you feel like it. 

Cheers.

**Pull request merged**
