### PR TITLE
Enable many more busybox applets

### PR DESCRIPTION
**Pull request by wdlkmpx**
Almost every applet is enabled now (359)

Surprisingly the busybox binary is still quite small
and compiles in i486, x86_64, and arm.

I want busybox to be treated differently from all the other programs.

The same binary produced here should go the main SFS, because it's
lightweight and practically complete (it does work in any puppy and boots
to desktop).

Aside from the mandatory symlinks, the build scripts should create
extra symlinks to busybox in /usr/local/bin/busybox/
(that directory should be added to the $PATH as the last dir)

That way users will be surprised to find out that every command they type it's already there,
if it's missing features, they can still install the full versions afterwards
without causing any problems because the extra busybox symlinks are the last resort.

This could be useful to identify which busybox apps work exactly the same
as the full versions, making the busybox app the default one, saving space...

### CODE REVIEW

**Comment by jamesbond3142** [comment]
It's good idea to have full busybox in initrd (I do it in Fatdog). It's also good idea to have full busybox in basesfs. But don't use the same copy for initrd and basesfs. They are meant and optimised to do different things. Just two examples:
a) initrd busybox is compiled statically _not_ using glibc. Thus certain glibc features won't be used in static busybox. E.g "busybox date" on static busybox will return the wrong time if TZ env variable is set according to glibc conventions (usually TZ=:/etc/localtime and /etc/localtime is a symlink to the actual timezone info file) - because uclibc/musl doesn't recognise glibc's timezone. 
b) for speed, you may want to static busybox with PREFER_APPLET and NO_FORK_APPLET in the static busybox. This speeds up initscripts as it tells busybox applets directly without having to search the filesystem for the utilities. But you don't want to do this on basesfs scripts. You want them to use the full utilities when they exist, and only fallback to busybox if they don't.

So, have full busybox in both initrd and basesfs. Build the one for initrd as static, with PREFER_APPLET and perhaps also NO_FORK_APPLET. Build the one for basesfs as dynamic, using glibc. Do keep a copy of static busybox in basesfs too, the rare case where you need a busybox that doesn't depend on glibc. Then you have the best of both worlds.

**Comment by jamesbond3142** [comment]
On Sun, 29 May 2016 14:02:07 -0700
wdlkmpx notifications@github.com wrote:

> The same binary produced here should go the main SFS, because it's
> lightweight and practically complete (it does work in any puppy and boots
> to desktop).

No please don't. Static busybox doesn't recognise glibc conventions. Try to run "busybox date" with a static busybox, with a Puppy (or any Linux system, actually) that is fully configured. I bet you get a wrong date.

Your idea is good, it is a good idea that the basesfs has full-featured busybox as a fallback for when the full utilities aren't available. But build them separately - the one for basesfs should be linked against glibc.

cheers!

**Comment by 01micko** [comment]
Since this PR doesn't affect whatever is included in the main distro I'm merging.

Carry on the insightful discussion at will. :smile:

**Comment by wdlkmpx** [comment]
Ok thanks, I'll use PREFER_APPLET, I can't find NO_FORK_APPLET in the config.

As the config file and patches will be the same for both static and shared busyboxes, this  '# CONFIG_FEATURE_PREFER_APPLETS is not set' will become 'CONFIG_FEATURE_PREFER_APPLETS=y' just before compiling the static version

**Comment by wdlkmpx** [comment]
So now that I applied practically all the changes I planned. I think i'll be checking out the petbuilds repo..... but I want to simplify everything.

I edited the busybox lspci and added code to print elspci output... worked exactly the same, but then there were a few differences in some specific "classes" here and there. I accidentally deleted it when I deleted that busybox directory. However I have a elspci edited to be more understandable (no code changes) and it's easy for me to make a busybox applet of it.

Having said that, to reduce the number of petbuilds... I think it's a good idea to merge all tiny apps into busybox... busybox will grow 1kb if it's really tiny and properly merged or ~5k with the full version.. this is the place to do that before moving to check other repos...

**Comment by 01micko** [comment]
`pet_builds` by design is kind of a 'modular' repo. Probably best if you create a new branch based on the slacko branch and I'll pull in whatever changes I like to my next slacko branch by creating a branch from your work.

**Comment by wdlkmpx** [comment]
Yeah you're right, but i was thinking something beyond that... that includes DISTRO_PKGS_SPECS, the pet repos, etc, etc. to just delete as many as entries as possible. 

I also think the pet_builds should have only 1 branch... with different directories that use the same build script.

Even the petbuilds can be somewhat unified... with some rules in config file (taking into account the DISTRO_SPECS), etc...

I see you want to build a minimun working puppy... in 2014-2015 i achieved that i was building the only puppy i built so far. DISTRO_PKGS_SPECS has to have some sort of order, I mean... separate blocks of pkgs with comments to identify the priority.

Of course i can contribute code and make things work, but i'm not sure if i'll be able to finish my work or if it even be worthwhile as I see my room become full of spiders web, it's funny i should sell everything i have haha

**Comment by 01micko** [comment]
I am at the point where I think that woof should be re-written from scratch. I certainly don't have the time to do that so fixes and enhancements are bolted on making it look horribly cumbersome.

Perhaps we should make a new branch 'legacy' << 'master' mainly to preserve the old code with a note that if you use this branch 'you are on your own'. That leaves us with the room to make more radical changes and rationalisations in 'testing'.

The 'end user' makes a lot of demands these days. Not only do they want their old pIII to work but they expect that the same iso will boot and run on their you beaut core i7 lappy with touch screen. That is the reality and also the difficulty. My last pIII (my eee 701SD) has now decided to cease working (keyboard). I've lost 4 old computers in the last year. Oldest ones now are an athlon 1900 and celeron 2.4GHz (basically p4 architecture). Both are rarely booted due to space constraints at my house.

Current working stock are my X2 athlon, 2 dell optiplex 760s, an HP/compaq lappy (core2 duo) and the Acer w500 tablet (for which working touchscreen is essential - comes with a crap keyboard but.. )

I'm open to the idea of having `zdrv` load by default but 'kernel-kit' will then have to have all firmware removed from the kernel sfs. There is absolutely no point in having redundant firmware and is a complete waste of space. This also opens up the prospects for true frugalists to cut down their own firmware based on their own hardware. Should be pretty simple to make an 'fdrv_cutter' and also improve upon @technosaurus ' ['zdrv_cutter'](http://murga-linux.com/puppy/viewtopic.php?t=51552).

**Comment by wdlkmpx** [comment]
I guess this reply was meant for puppylinux-woof-CE/woof-CE#788 ?

Well, there should be no fear in changing, the past and the current puppies work, people can stick to those if they wish, it's 2016, it's time look to other directions. For video they compile a new mplayer and it's all working again, for www, they already have the solution, so basically that's it.

There's also very broken variants, such as Arch (this one is extremely good, but they lost their way with systemd), and the other ones....  some of them probably forgotten for years.. you know what I mean.

I even used a 4.4 kernel in my extremely slow p4 celeron pc... worked as fast as the precise retro I always used, with a couple issues resolved in my hybrid rc.sysinit. So, to be honest, leaving the old code behind in a legacy branch is the way to go.

I use a big puppy in a machine with very low ram... just avoid copying the main sfs to ram, and it just works the same.. so for me, it doesn't matter if there are 200MB in a drv.sfs or 500MB in the main sfs and having 256MB of ram. Of course that is a in hard disk... i have like 10 very old hds that i'm trying to kill one by one, but it doesn't happen.

Also, as life goes by so fast, i would say that changes happen in a frenetic, psychotic pace, I mean, just getting rid of old stuff, configs, etc. ...

**Comment by wdlkmpx** [comment]
Graphic description 
capture27115

**Comment by wdlkmpx** [comment]
You might want to publish a roadmap to enlighten about the plans.

I also want to write about some ideas and explain carefully what I have in mind, but i said this before, I actually have some problems writing and writing... i have to think twice, check my spelling like 4 times and will still write nonsense that can be easily found in a google search. I don't feel comfortable. Although reading Pelo's or oui's comments after 2000+ posts... relieves me a bit.

**Comment by 01micko** [comment]
> You might want to publish a roadmap to enlighten about the plans.

I think I will do this on [the blog](blog.puppylinux.com).

I've lost interest in the nabble forum. Spam was becoming a PITA and I might close it.

**Comment by 01micko** [comment]
Done.

http://blog.puppylinux.com/?viewDetailed=00025

**Comment by wdlkmpx** [comment]
I'm very pleased to read that. So looking forward to see it happen.

So I was thinking about applying the same logic to build the kernel,
but first I wonder how to create a 64 bit arm initrd.gz

The solution could be here http://autobuild.buildroot.org/toolchains/tarballs/

I sent an email to Rob, asking to update a bit, he said he's not using
GPLv3 software, so that he has to use old versions of gcc, binutils. I
think his work is what best fits the project, small, it works,
readable scripts and targets already configured.. that produces a
cross compiler and a small system image ready to boot (need to provide
kernel and initrd), I mean everything seems to be there (and -small-),
but there's a problem.

I think I'll edit his scripts and try to build updated toolchains to
produce the same results and and add armv7.. aarch64 (amrv8) is not
supported by musl according to the outdated musl wiki (2014), or
perhaps I should use Sabotage.. need advice to avoid doing and redoing
things

**Pull request merged**
