### PR TITLE
Heavy updates

### PR DESCRIPTION
**Pull request by wdlkmpx**
With these changes and downloading a recent cross compiler from
aboriginal linux, it compiles in slacko and tahrpup the following static apps:

```
awk bash blkid busybox cp disktype e2fsck e3 elspci find
fsck fusermount grep guess_fstype losetup lsmod modinfo
modprobe ntfs-3g resize2fs sed unshare vercmp waitmax xargs
```

It also creates a working initrd.gz and packages some stuff for distribution.

All apps are updated to the latest version.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I tested a static bash as the init shell... it makes no difference. the latest version of busybox has many fixes and also supports more options for a number of applets, I think busybox could also do the job... but busybox would not compile if grep is enabled. It looks like musl regex lib is missing functions.

One app that is really not needed is xargs... it's used once and that code can easily be replaced with shell code (while loop).

So, with this new stuff, there are new possibilities...

**Comment by 01micko** [comment]
yeah I don't think bash is needed, ash does the job.

The whole init should be rewritten with way less external calls.

bug in func @ line 30 :wink:

**Comment by 01micko** [comment]
Mostly worked except hung up on `disktype`.  Moved it to sources and kept going. 

i suppose I'll test out the produced initrd.gz later.

**Comment by wdlkmpx** [comment]
I just run the script in slacko64, there were no errors to stop the process, but busybox is linked to static glibc libs I guess. it's 2mb (all the other apps are ok), that doesnt happen in tahrpup/tahrpup64 and slacko32, where the size is about 550k with many features. All in all it was a good exercise

**Pull request merged**
