### PR TITLE
updates

### PR DESCRIPTION
**Pull request by wdlkmpx**
- build.conf: disable module-init-tools_static
- init: delete useless umntfunc
- build.sh: add -clean option
- remove e3, waitmax script
- mp: smaller size
- build.conf: disable coreutils, patch for busybox cp
- guess_fstype is now a busybox applet (jamesbond)
- waitmax is now a busybox applet
- vercmp is now a busybox applet
- move busybox patches to their own dir
- build.conf: disable findutils, use busybox find
- func: create make.sh in source dir
- busybox vercmp: misc edits
- build.conf: fsck is now a symlink to e2fsck

### CODE REVIEW

**Comment by wdlkmpx** [comment]
In https://github.com/puppylinux-woof-CE/initrd_progs/pull/6/commits/ad93a734672d741ccd2a13c6d554dad793bae04a I added static fsck.fat, I remember rsncss51 said once that some old pcs will only work with fat formatted usbs (for a frugall install or something like that), certainly mine does not with usb, but with the hybrid puppy usb it does show the splash, but it gets stuck there.... i wonder if adding code to fsck a fat partition from the initrd would be worthwhile

**Comment by wdlkmpx** [comment]
The cp patch for busybox in https://github.com/puppylinux-woof-CE/initrd_progs/pull/6/commits/a82e52731dfc264dfb8f3268ec0a35308d9466fd has been revised and merged into busybox.. when 1.25 comes out I'll remove the patch

**Comment by 01micko** [comment]
I'll give this a test tomorrow (AEST) - about 14 hrs from now. Been a big week for me.

**Comment by wdlkmpx** [comment]
The initrd can also be xz compressed. So I added a commit that enables that, and made misc edits to replace initrd.gz with initrd.gz/xz everywhere.

So I booted with a initrd.xz (1mb) and it worked (had to alter the bootloader menu).

But now that I renamed initrd.xz to initrd.gz and seeing that it works the same... the kernel does not care about extensions, I guess I should redo the commit to just use initrd.gz no matter the compression method... zzz

I recommend using xz compression for the initrd from now on, I think I'll also enable as many busybox applets as possible... so initrd remains quite small (1mb-1.5mb) and can have a mini distro inside, a complete set of tools of every kind

**Comment by 01micko** [comment]
That sounds good. Still haven't had a chance to test but will soon.

**Comment by wdlkmpx** [comment]
Well, since commit https://github.com/puppylinux-woof-CE/initrd_progs/pull/6/commits/5323b0a3142aea1c2f7b3db3c00b02f1461a618c you just type `./build.sh xz` and the result will be a xz compressed initrd.gz 

Then it's ready to be tested.

**Comment by 01micko** [comment]
Works!

**Pull request merged**
